spring:
  jackson:
    generator:
      write-bigdecimal-as-plain: true
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-zone-id: true
      indent-output: true
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      email: unknown@example.com
      first-name: Curtis
      last-name: Newton
    deployment-resource-pattern:
    - classpath:/processes/**/*.bpmn
    default-serialization-format: application/json
